name: Icon request
description: Submit an icon request
title: "Icon request: Team name"
labels: ["icon request"]
body:
  - type: markdown
    attributes: 
      value: "Form for icons in Pro"
  - type: textarea
    id: filename
    attributes:
      label: File name 
      description: Name of the icon file to be created.
      placeholder: This should match what will be in the repo and referenced in the code.
      value: BuildingFootprint
    validations:
      required: true
  - type: checkboxes
    id: icon-size
    attributes:
      label: Sizes needed
      description: What sizes are needed for this icon?
      options:
        -label: "12x12"
        -label: "16x16"
        -label: "24x24"
        -label: "32x32"
        -label: "48x48"
    validations:
      required: true
  - type: textarea
    id: descNotes
    attributes:
      label: Description/Notes
      placeholder: A description of the command or option that goes with the icon
      value: "None"
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Alt text
      description: The name of the command or option in the UI.
      placeholder: This appears as the heading for the ScreenTip or the name of an option.
      value: "None"
    validations:
      required: true
