name: Icon request
description: Submit an icon request
title: "Icon request: Team name"
labels: ["icon request"]
body:
  - type: markdown
    attributes: 
      value: "Form for icons in Pro"
  - type: textarea
    id: filename
    attributes:
      label: File name 
      description: Name of the icon file to be created.
      placeholder: This should match what will be in the repo and referenced in the code.
      value: BuildingFootprint
    validations:
      required: true
  - type: checkboxes
    id: icon-size
    attributes:
      label: Sizes needed
      description: What sizes are needed for this icon?
      options:
        -label: twelve by twelve (12x12)
        -label: sixteen by sixteen (16x16)
        -label: twenty-four by twenty-four (24x24)
        -label: thirty-two by thirty-two (32x32)
        -label: forty-eight by forty-eight (48x48)
    validations:
      required: true
  - type: textarea
    id: descNotes
    attributes:
      label: Description/Notes
      placeholder: A description of the command or option that goes with the icon
      value: "None"
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Alt text
      description: The name of the command or option in the UI.
      placeholder: This appears as the heading for the ScreenTip or the name of an option.
      value: "None"
    validations:
      required: true
